force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child (Lookup)</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Child (Lookup)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Child (Lookup)</relationshipLabel>
    <relationshipName>Child_Lookup</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Child_MasterDetail__c/Child_MasterDetail__c.object-meta.xml
<CustomObject>
    <label>Child (MasterDetail)</label>
    <nameField>
        <label>Child (MasterDetail) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Child (MasterDetail)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Child_MasterDetail__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <referenceTo>Parent__c</referenceTo>
    <relationshipLabel>Child (MasterDetail)</relationshipLabel>
    <relationshipName>Child_MasterDetail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Parent__c/Parent__c.object-meta.xml
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Parent__c/fields/Sensitive_Data__c.field-meta.xml
<CustomField>
    <fullName>Sensitive_Data__c</fullName>
    <label>Sensitive Data</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Demo_DataSecuritySettingsController.cls
public with sharing class Demo_DataSecuritySettingsController {
    @AuraEnabled(cacheable=true)
    public static List<Parent__c> getParents(Boolean withUserContext)
    {
        try {
            if (withUserContext) {
                return [SELECT Id, Name, Sensitive_Data__c FROM Parent__c ORDER BY Name ASC];
            } else {
                SharingSettingByPassHelper helper = new SharingSettingByPassHelper();
                return helper.getParentsWithSystemContext();
            }
        } catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
        
    }

    @AuraEnabled(cacheable=true)
    public static List<Child__c> getChildLookup(String parentId, Boolean withUserContext)
    {
        try {
            if (withUserContext) {
                return [SELECT Id, Name, Sensitive_Data__c FROM Child__c WHERE Parent__c = :parentId ORDER BY Name ASC];
            } else {
                SharingSettingByPassHelper helper = new SharingSettingByPassHelper();
                return helper.getChildLookupWithSystemContext(parentId);
            }
        } catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Child_MasterDetail__c> getChildMasterDetail(String parentId, Boolean withUserContext)
    {
        try {
            if (withUserContext) {
                return [SELECT Id, Name FROM Child_MasterDetail__c WHERE Parent__c = :parentId ORDER BY Name ASC];
            } else {
                SharingSettingByPassHelper helper = new SharingSettingByPassHelper();
                return helper.getChildMasterDetailWithSystemContext(parentId);
            }
        } catch (Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public without sharing class SharingSettingByPassHelper
    {
        public List<Parent__c> getParentsWithSystemContext()
        {
            return [SELECT Id, Name, Sensitive_Data__c FROM Parent__c ORDER BY Name ASC];
        }

        public List<Child__c> getChildLookupWithSystemContext(String parentId)
        {
            return [SELECT Id, Name, Sensitive_Data__c FROM Child__c WHERE Parent__c = :parentId ORDER BY Name ASC];
        }

        public List<Child_MasterDetail__c> getChildMasterDetailWithSystemContext(String parentId)
        {
            return [SELECT Id, Name FROM Child_MasterDetail__c WHERE Parent__c = :parentId ORDER BY Name ASC];
        }
    }
}